<a href="https://colab.research.google.com/github/dann4832022/Proyecto-Cine/blob/main/An%C3%A1lisis_de_Datos_Clase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analisis de datos

## 1 ETL ( Extracción, Transformación y carga)

In [42]:
from google.colab import drive
#drive.mount('/content/drive/drive/MyDrive', descarga (1)=True)

import pandas as pd
import chardet
ruta_archivo = '/content/drive/MyDrive/ventas.csv'
with open(ruta_archivo, 'rb') as f:
    result = chardet.detect(f.read())
    print(result)
try:
  df= pd.read_csv(ruta_archivo, encoding=result['encoding'], sep=';', decimal=',')
  print("Extraccion de datos exitoosa")
except FileExistsError:
  print("Error en la extraccion de datos")

# 2 Transformacion

In [47]:
# Muestra las primeras 5 filas
df.head(10)

,tienda,marca,tipo,genero,talla,color,categoria,precio,fecha_hora
0,Lima,Asics,WB1820,F,42,Azul,Pantalon,89.00,2015-07-15 07:32:00
1,Lima,Asics,Kayano Single Tab,U,42-44,Azul,Ropa interior,24.99,2015-07-15 07:33:00
2,Lima,Asics,WB1820,F,37,Rosado,Pantalon,89.00,2015-07-15 07:52:00
3,Lima,Asics,WB2585,F,39,Negro,Pantalon,99.00,2015-07-15 07:58:00
4,Lima,Asics,WB1820,F,46,Multicolor,Pantalon,89.00,2015-07-15 08:19:00
5,Lima,Asics,WB1820,F,39,Azul,Pantalon,89.00,2015-07-15 08:48:00
6,Lima,Asics,MB1878,M,38,Negro,Pantalon,99.00,2015-07-15 09:07:00
7,Lima,Asics,Hera Deux Single Tab,F,42-44,Negro,Ropa interior,12.99,2015-07-15 09:11:00
8,Lima,Asics,MB1878,M,38,Negro,Pantalon,99.00,2015-07-15 10:04:00
9,Lima,Asics,MB1878,M,46,Negro,Pantalon,99.00,2015-07-15 10:06:00

In [6]:
# Resumen de la información del dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 727 entries, 0 to 799
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tienda     727 non-null    object
 1   marca      727 non-null    object
 2   tipo       727 non-null    object
 3   genero     727 non-null    object
 4   talla      727 non-null    Int64
 5   color      727 non-null    object
 6   categoria  727 non-null    object
 7   precio     727 non-null    float64
 8   fecha      727 non-null    object
 9   hora       727 non-null    object
dtypes: Int64(1), float64(1), object(8)
memory usage: 63.2+ KB

In [4]:
# Generar estasdisticas descriptivas de las columnas numéricas
df.describe()

,Tienda,Marca,Tipo,Gï¿½nero,Talla,Color,Categoria,precio de venta,Fecha,Hora
count,800,800,800,800,800,800,800,800,800,800
unique,2,3,21,3,47,7,4,20,8,489
top,Lima,Asics,WB1820,Femenino,41,Negro,Pantalon,89,16/07/2015,14:52:00
freq,578,501,195,375,59,261,331,194,150,6

In [43]:
#Renombrar columnas para faciliar el acceso y evitar caracteres especiales
df.rename(columns={
    'Tienda': 'tienda',
    'Marca': 'marca',
    'Tipo': 'tipo',
    'Gï¿½nero': 'genero',
    'Talla': 'talla',
    'Color': 'color',
    'Categoria': 'categoria',
    'precio de venta': 'precio',
    'Fecha': 'fecha',
    'Hora': 'hora'
}, inplace=True)

In [44]:
#convertir la columna precio a numérico
df['precio']=df['precio'].astype(str)
df['precio']=df['precio'].str.replace(',','.', regex=True).astype(float)


#print(set(df['genero'])) ver y obtener informacion resultado {'Usinex', 'Masculino', 'Femenino'}
#Cambiar el nombre de las columnas
df['genero'] = df['genero'].str.replace('Masculino','M', regex=False)
df['genero'] = df['genero'].str.replace('Femenino','F', regex=False)
df['genero'] = df['genero'].str.replace('Usinex','U', regex=False)

#Crear columnas de fecha y horas combinadas y convertilas al tipo datatime
df['fecha_hora'] = pd.to_datetime(df['fecha'] + ' ' + df['hora'], format='%d/%m/%Y %H:%M:%S')

print(df['talla'].unique())

#print(df.head())
#eliminar columnas de fecha y hora
df.drop(['fecha', 'hora'], axis=1, inplace=True)
#print(df.head())

#Dedocraticamenete tomamos las primera aparición numérica y descartamos el resto.
#Tomamos el valor de la izquerda si hay un guion

#df['talla'] = df['talla'].astype(str).apply(lambda x: x.split('-')[0])
#ahora lo convertimos a tipo numerico
#df['talla'] = pd.to_numeric(df['talla'], errors='coerce').astype('Int64')
#Eliminar fila con tallas mala  o no numéricas despues de la conversión
#df.dropna(subset=['talla'], inplace=True)

print(set(df['genero']))
print("Transformacion de datos exitosa")

['42' '42-44' '37' '39' '46' '38' '38-40' '44' '40' '70F' '41' '45'
 '36-38' '40-42' '46-48' '80A' '80B' '80C' '43' '36' '80F' '44-46' '85F'
 '70B' '80E' '90B' '90F' '65D' '70D' '75D' '70E' '90E' '85D' '65E' '75A'
 '75B' '80D' '85A' '75E' '65B' '75F' '90D' '85C' '65F' '75C' '65A' '65C']
{'F', 'M', 'U'}
Transformacion de datos exitosa

In [28]:
print(df.groupby('categoria')['talla'].unique())

categoria
Pantalon              [42, 37, 39, 46, 38, 40, 41, 45, 43, 36, 44]
Ropa interior           [42-44, 38-40, 36-38, 40-42, 46-48, 44-46]
Sujetadores      [70F, 80A, 80B, 80C, 80F, 85F, 70B, 80E, 90B, ...
Zapatillas            [44, 39, 42, 37, 38, 41, 40, 43, 45, 46, 36]
Name: talla, dtype: object

In [31]:
tallas_sujetadores = df[df['categoria'] == 'Sujetadores']['talla'].unique()

print(tallas_sujetadores)

['70F' '80A' '80B' '80C' '80F' '85F' '70B' '80E' '90B' '90F' '65D' '70D'
 '75D' '70E' '90E' '85D' '65E' '75A' '75B' '80D' '85A' '75E' '65B' '75F'
 '90D' '85C' '65F' '75C' '65A' '65C']

In [39]:
print(df.groupby('tipo')['talla'].unique())

tipo
Air Zoom                                                [42, 44, 38, 45, 36, 43, 39, 40]
Boston 5                                            [36, 42, 37, 40, 46, 41, 43, 39, 44]
Cummulus 17                                 [44, 38, 39, 40, 41, 46, 43, 37, 45, 36, 42]
Dri-Fit No-Show                               [40-42, 42-44, 46-48, 44-46, 38-40, 36-38]
Free 5.0                                        [38, 40, 43, 45, 37, 42, 46, 36, 44, 39]
Gel Quantics                                                                [37, 46, 41]
Hera Deux Single Tab                          [42-44, 40-42, 46-48, 38-40, 36-38, 44-46]
Hyper Elite Crew                              [38-40, 44-46, 40-42, 42-44, 36-38, 46-48]
Kayano Single Tab                             [42-44, 44-46, 36-38, 46-48, 40-42, 38-40]
MB1878                                      [38, 46, 37, 40, 44, 42, 43, 41, 39, 36, 45]
Nike Elite Match Fit Mercurial Crew           [38-40, 36-38, 42-44, 46-48, 40-42, 44-46]
Nimbus 17                                                   [39, 41, 44, 46, 42, 38, 43]
Pro Classic                                          [70F, 70E, 65E, 75B, 75F, 90F, 75E]
Pro Fierce                             [70F, 80B, 80C, 85F, 70B, 90B, 90F, 90E, 70D, ...
Pro Hero                               [80A, 65D, 70D, 75D, 80D, 85F, 80B, 65B, 90D, ...
Pro Indy                                        [80F, 80E, 85D, 70F, 65E, 70D, 70E, 65C]
Quick Light Cushion                           [36-38, 40-42, 46-48, 42-44, 38-40, 44-46]
Rocket Boost                                        [43, 46, 39, 45, 41, 36, 44, 37, 40]
Ultra Boost                                                     [41, 46, 36, 44, 39, 38]
WB1820                                      [42, 37, 46, 39, 40, 41, 45, 38, 43, 36, 44]
WB2585                                          [39, 46, 40, 44, 41, 38, 37, 36, 45, 43]
Name: talla, dtype: object

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tienda      800 non-null    object
 1   marca       800 non-null    object
 2   tipo        800 non-null    object
 3   genero      800 non-null    object
 4   talla       800 non-null    object
 5   color       800 non-null    object
 6   categoria   800 non-null    object
 7   precio      800 non-null    float64
 8   fecha_hora  800 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 56.4+ KB

#3 Carga(Load)

In [48]:
#Definir la ruta de salida para guardar el nuevo csv

ruta_salida = '/content/drive/MyDrive/ventas_transformadas.csv'

# guardar el dataframe transformado en un nuevo archivo csv en drive
df.to_csv(ruta_salida, index=False, sep=',')

print(f"Archivo guardado en: {ruta_salida}")

Archivo guardado en: /content/drive/MyDrive/ventas_transformadas.csv